# Generated by Django 4.2.16 on 2024-10-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "high_level",
            "0003_remove_machine_objet_ptr_remove_produit_objet_ptr_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ville",
            name="population",
            field=models.IntegerField(default=0),
        ),
    ]
