# Generated by Django 4.2.16 on 2024-10-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "high_level",
            "0006_remove_machine_objet_ptr_remove_produit_objet_ptr_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ville",
            name="population",
        ),
        migrations.AlterField(
            model_name="ville",
            name="code_postal",
            field=models.CharField(max_length=10),
        ),
    ]
