# Generated by Django 4.2.16 on 2024-10-04 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("high_level", "0007_remove_ville_population_alter_ville_code_postal"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recette",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="RecetteIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "recette",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="high_level.recette",
                    ),
                ),
                (
                    "ressource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="high_level.ressource",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="recette",
            name="ingredients",
            field=models.ManyToManyField(
                through="high_level.RecetteIngredient", to="high_level.ressource"
            ),
        ),
    ]
