# Generated by Django 4.2.16 on 2024-10-04 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("high_level", "0009_usine_ressources"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produit",
            name="objet_ptr",
        ),
        migrations.RemoveField(
            model_name="produit",
            name="premiere_etape",
        ),
        migrations.RemoveField(
            model_name="quantiteressource",
            name="ressource",
        ),
        migrations.RemoveField(
            model_name="usine",
            name="ressources",
        ),
        migrations.DeleteModel(
            name="Etape",
        ),
        migrations.DeleteModel(
            name="Produit",
        ),
        migrations.DeleteModel(
            name="QuantiteRessource",
        ),
    ]
